export const SET_PDKS_XLSX = "SET_PDKS_XLSX";
export const SET_PDKS_OUTPUT = "SET_PDKS_OUTPUT";
export const SET_GUN_SAYISI_XLSX = "SET_GUN_SAYISI_XLSX";
export const SET_GUN_SAYISI_OUTPUT = "SET_GUN_SAYISI_OUTPUT";
export const SET_PDKS_IST_XLSX = "SET_PDKS_IST_XLSX";
export const SET_PDKS_IST_OUTPUT = "SET_PDKS_IST_OUTPUT";


